fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /login

hwi_github_login:
    pattern: /login/check-github

ac_web:
    resource: "@ApproveCodeWebBundle/Resources/config/routing.yml"

ac_repository:
    resource: "@ApproveCodeRepositoryBundle/Resources/config/routing.yml"