security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        manage:
            pattern: ^/
            oauth:
                login_path:         /login/github

                provider: fos_userbundle
                resource_owners:
                    github: /login/check-github
                oauth_user_provider:
                    service: ac.user.provider.github_user

            anonymous: true
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/repository, role: ROLE_USER }
