ac_repository_repository_list:
    path:     /repository/list
    defaults: { _controller: ApproveCodeRepositoryBundle:Repository:list }

ac_repository_repository_sync:
    path:     /repository/sync
    defaults: { _controller: ApproveCodeRepositoryBundle:Repository:sync }

ac_reposiory_repository_toggle:
    path:     /repository/toggle/{repository}
    defaults: { _controller: ApproveCodeRepositoryBundle:Repository:toggle }
    options:
        expose: true
