services:
    ac.repository.service.repository_synchronizer:
        class: ApproveCode\Bundle\RepositoryBundle\Service\RepositorySynchronizer
        arguments:
            - @ac.api.manager.github_webhook_manager
            - @doctrine
