services:
    ac.repository.service.repository_synchronizer:
        class: ApproveCode\Bundle\RepositoryBundle\Service\RepositorySynchronizer
        arguments:
            - @ac.api.wrapper.github_api_wrapper
            - @doctrine
