parameters:
    ac.webhook.helper.security.class: ApproveCode\Bundle\WebhookBundle\Helper\SecurityHelper
    ac.webhook.handler.github_event.class: ApproveCode\Bundle\WebhookBundle\Handler\GithubEventHandler
    ac.webhook.handler.github.pull_request_open.class: ApproveCode\Bundle\WebhookBundle\Handler\Github\PullRequestOpenHandler
    ac.webhook.handler.github.pull_request_comment.class: ApproveCode\Bundle\WebhookBundle\Handler\Github\PullRequestReviewCommentHandler
services:
    ac.webhook.helper.security:
        class: %ac.webhook.helper.security.class%
        arguments:
            - %webhook_secret%

    ac.webhook.handler.github_event:
        class: %ac.webhook.handler.github_event.class%
        calls:
            # TODO: Collect handlers by tags in compiler pass
            - [addEventHandler, [@ac.webhook.handler.github.pull_request_open]]
            - [addEventHandler, [@ac.webhook.handler.github.pull_request_comment]]

    ac.webhook.handler.github.pull_request_open:
        class: %ac.webhook.handler.github.pull_request_open.class%
        arguments:
            - @doctrine
            - @ac.api.github.client_factory
            - %status_context%

    ac.webhook.handler.github.pull_request_comment:
        class: %ac.webhook.handler.github.pull_request_comment.class%
        arguments:
            - @doctrine
            - @ac.api.github.client_factory
            - %status_context%
