parameters:
    ac.webhook.helper.security.class: ApproveCode\Bundle\WebhookBundle\Helper\SecurityHelper
    ac.webhook.helper.status_marker.class: ApproveCode\Bundle\WebhookBundle\Helper\StatusMarkerHelper
    ac.webhook.manager.webhook_manager.class: ApproveCode\Bundle\WebhookBundle\Manager\WebhookManager

services:
    ac.webhook.helper.security:
        class: %ac.webhook.helper.security.class%
        arguments:
            - %webhook_secret%

    ac.webhook.helper.status_marker:
        class: %ac.webhook.helper.status_marker.class%

    ac.webhook.manager.webhook_manager:
        class: %ac.webhook.manager.webhook_manager.class%
        arguments:
            - @doctrine
            - @security.token_storage
            - @ac.github.manager.github_manager
