services:
    ac.api.manager.github_webhook_manager:
        class: ApproveCode\Bundle\ApiBundle\Manager\GithubWebhookManager
        arguments:
            - @security.token_storage
            - @github_api
